name: Trivy IaC Security Scan

on:
  push:         # triggers on every push 
    branches: ['**']
  pull_request:
    branches:
      - dev
      - prd

permissions:
  contents: read

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy IaC scan 
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'repo'
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  #  does not fail, just the output

      - name: Upload Trivy results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-${{ github.run_id }}
          path: trivy-results.sarif
