name: Terraform Validate & Plan
run-name: Terraform Validation and Plan in Branch ${{ github.ref_name }} # Run Number ${{ github.run_number }}s

on:
  push:
    branches: ['**']

permissions:
  contents: read

jobs:
  terraform-validate-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0 

      - name: Terraform Init
        run: terraform init
        working-directory: dev

      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan (readable)
        id: plan
        run: |
          terraform plan | tee ./tfplan.txt
        working-directory: dev  

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.run_id }}
          path: dev/tfplan.txt