name: Terraform Validate & Plan
run-name: Terraform Validation and Plan in Branch ${{ github.ref_name }} # Run Number ${{ github.run_number }}s

on:
  push:
    branches: ['**']

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CICD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0 

      - name: Terraform Init
        run: terraform -chdir=dev init -backend-config=backend.tf

      - name: Terraform Validate
        run: terraform -chdir=dev validate
      - name: Terraform Plan (readable)
        id: plan
        run: |
          terraform -chdir=dev plan -var-file=dev/terraform.tfvars | tee dev/tfplan.txt

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.run_id }}
          path: dev/tfplan.txt